[build]
  base = "frontend"
  publish = "."
  command = "node build-config.js && echo Static site build-ready"

[build.environment]
  NODE_VERSION = "20.17.0"
  # Exclude the generated config (contains search-only key) from secrets scanning
  SECRETS_SCAN_OMIT_PATHS = "frontend/config.js"
  # Omit non-secret constant values (like index name) from secret detection
  SECRETS_SCAN_OMIT_KEYS = "ALGOLIA_INDEX_NAME"

