[build]
  base = "frontend"
  publish = "."
  command = "node build-config.js && echo Static site build-ready"

[build.environment]
  NODE_VERSION = "20.17.0"
  # Exclude the generated config (contains search-only key) from secrets scanning
  SECRETS_SCAN_OMIT_PATHS = "config.js"
  # Omit known non-sensitive env keys used in the frontend
  SECRETS_SCAN_OMIT_KEYS = "ALGOLIA_INDEX_NAME,ALGOLIA_APPLICATION_ID,ALGOLIA_SEARCH_API_KEY"

